---
- hosts: berry
  remote_user: pi
  become: yes

  # roles:
  # - mpd_rpi


- hosts: berry
  remote_user: pi

  tasks:
  - name: Checkout source
    git:
      repo: https://github.com/sebaacuna/lias-turntable.git
      dest: /home/pi/lias-turntable
      accept_hostkey: true

  - name: Install requirements
    pip:
      executable: pip3
      requirements: /home/pi/lias-turntable/requirements.txt

  - name: Install package
    pip:
      executable: pip3
      name: /home/pi/lias-turntable
      editable: yes

  - name: Checkout PIRC source
    git:
      repo: https://github.com/sebaacuna/pi-rc522.git
      dest: /home/pi/pi-rc522
      accept_hostkey: true

  - name: Install pi-rc522
    pip:
      executable: pip3
      name: /home/pi/pi-rc522
      editable: yes

  - name: Enable SPI
    become: yes
    blockinfile:
      path: /boot/config.txt
      block: dtparam=spi=on
