---
- hosts: berry
  remote_user: pi

  tasks:
  - name: Install requirements
    pip:
      virtualenv: /home/pi/venv
      requirements: /home/pi/lias-turntable/requirements.txt

  - name: Install package
    pip:
      virtualenv: /home/pi/venv
      name: /home/pi/lias-turntable
      editable: yes

  - name: Install pi-rc522
    pip:
      virtualenv: /home/pi/venv
      name: git+https://github.com/ondryaso/pi-rc522.git#egg=pi-rc522
      editable: yes
