---
- hosts: berry
  remote_user: pi

  tasks:
  - name: Install requirements
    pip:
      virtualenv: /home/pi/venv
      requirements: /home/pi/lias-turntable/requirements.txt

  - name: Install package
    pip:
      virtualenv: /home/pi/venv
      name: /home/pi/lias-turntable
      editable: yes

